advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path,re_path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # re_path(r'^$', views.index, name='Index'),
    path('index/', views.CBView.as_view(), name='Index'),
    re_path(r'^$', views.IndexView.as_view(), name='IndexView'),
    path('basic_app/', include('basic_app.urls'), name='basic_app'),
]

advcbv/basic_app/urls.py
from django.urls import re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    re_path(r'^$', views.SchoolListView.as_view(), name='list'),
    # re_path(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view(), name='detail'),
    re_path(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    re_path(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    re_path(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principle = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={"pk":self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    # related_name relates in such a way we can get all the students in a perticular school
    #  from school table only something like school_details.students
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render

# for class based view
from django.views.generic import (View, TemplateView, 
                                ListView, DetailView, 
                                CreateView, UpdateView, 
                                DeleteView)
from django.urls import reverse_lazy
from django.http import HttpResponse
from .  import models

# Create your views here.
# def index(request):
#     return render(request,'index.py')

class CBView(View):
    def get(self,request):
        return HttpResponse("Class Based Views Are Cool!")

class IndexView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject_me'] = 'BASIC INJECTION!'
        return context


# Generic View

"""ListView makes the context dictionary itself and returns it so we do not have to do it externally
    in this case the context dict is school_list (lowercases models.Whatever and appends _list at the
    end so the name would be 'whatever_list') we can change the name using 'context_object_name = name' """

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    template_name = 'basic_app/school_list.html'
    # name changed from default school_list to schools
    


"""DetailView just return lowercase of models.Whatever.. whatever would be the name"""

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'
    # name changed from default school to school_detail


#it wants a default template of name school_form
class SchoolCreateView(CreateView):
    fields = ('name', 'principle', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principle')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <title>BASE</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark navbar-static-top" style="background-color:black;">
        <div class="container">
                <div><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</div>
                <div><a class="navbar-brand" style="color:white;" href="{% url 'admin:index' %}">Admin</a></div>
        </div>
    </nav>



    <div class="container">
        
        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<div style="margin-top: 5%">
    <h1>Delete {{school.name}}?</h1>
    <footer style="text-align:right;">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger mr-5" value="Submit">
            <!-- no spaces between pk=school.pk -->
            <a class="btn btn-brand" href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
        </form>
    </footer>
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>School Details:</h1>
        <p>Name : {{ school_detail.name }}</p>
        <p>principal : {{ school_detail.principle }}</p>
        <p>Location : {{ school_detail.location }}</p>
        <h3>Students:</h3>
        {% for student in  school_detail.students.all %}
            <p>{{ student.name }} who is {{ student.age }} years old.</p>
        {% endfor %}
        <br>
        <br>
        <div class="container">
            <div style="display:inline-block">
                <span style="padding-right: 10px;"><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}"> Update </a></span>
                <span><a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}"> Delete </a></span>
            </div>
        </div>
    </div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

    <h1>
        {% if not form.instance.pk %}
            Create School:
        {% else %}
            Update School:
        {% endif %}
    </h1>
    <div class="jumbotron">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="submit" class="btn btn-primary">
        </form>
    </div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>List of all the Schools</h1>
        <ol>
        {% for school in schools %}
            <h2><li><a href='{{ school.id }}'>{{ school.name }}</a></li></h2>
        {% endfor %}
        </ol>
    </div>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <title>BASE</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark navbar-static-top" style="background-color:black;">
        <div class="container">
                <div><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</div>
                <div><a class="navbar-brand" style="color:white;" href="{% url 'admin:index' %}">Admin</a></div>
        </div>
    </nav>



    <div class="container">
        
        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

advcbv/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Index</h1>
        <p><h2>Injected Content : <strong> {{ inject_me }} </strong></h2></p>

    
        <h1>Home Page!</h1>
    </div>

{% endblock %}