project3/basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

# Template tagging
app_name = 'basic_app'

urlpatterns = [
    re_path(r'^$', views.index, name='Index'),
    path('relative/', views.relative, name='Relative'),
    path('other/', views.other, name='Others')
]

project3/project3/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('child/', views.child, name='Child'),
    re_path(r'^$', views.index, name='Index'),
]

project3/basic_app/models.py
from django.db import models

# Create your models here.

project3/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def child(request):
    CONTEXT_DICT = {'text':'HELLO WORLD','number':100}
    return render(request,'basic_app/child.html', CONTEXT_DICT)

def relative(request):
    return render(request,'basic_app/relative_url.html')

project3/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Main page</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-static-top">
        <div class="container">
                <div><a class="navbar-brand" href="{% url 'Index' %}">HOME</div>
                <div><a class="navbar-link" style="color:white;" href="{% url 'admin:index' %}">Admin</a></div>
                <div><a class="navbar-link" style="color:white;" href="{% url 'basic_app:Others' %}">Others</a></div>
        </div>
    </nav>
    <div class="container">

        {% block body_block %}
        <!-- Anything that will be inherited will come inside here -->
        {% endblock %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
</body>
</html>

project3/templates/basic_app/child.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>This is Child.html</h1>
            <h2>This is an example of template inheritance</h2>
            <h1>{{ text|lower }}</h1>
            <!-- custom filter registered using register-->
            <h1>{{ text|cut:"HELLO" }}</h1>
            <h1>{{ number|add:"99" }}</h1>
            <!-- custom filter registered using annotation -->
            <h1>{{ text|cut:"WORLD" }}</h1>
        </div>
    {% endblock %}

project3/templates/basic_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to Index</h1>
    
</body>
</html>

project3/templates/basic_app/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to others</h1>
    
</body>
</html>

project3/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative URL</h1>
    <!-- 'Others' is the value of name variable that is set in the path for 'other' -->
    <a href="{% url 'basic_app:Others' %}">Click here to navigate to others.html</a>
    <br>
    <br>
    <br>
    <!-- use 'index' with admin -->
    <a href="{% url 'admin:index' %}">Link to the admin page</a>
    <br>
    <br>
    <br>
    <!-- name of the index url is 'Index' -->
    <a href="{% url 'Index' %}">Link to the index page</a>
    
</body>
</html>