learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='Register'),
    path('login/', views.user_login, name='user_login'),

]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='Index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name="Logout"),
    path('special/', views.special, name="special"),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

# Form starts here
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# imports for login functionality
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout


# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            # print(user_form.errors()+" <--=+=--> "+ profile_form.errors())
            print('error')
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})




def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # django authenticate these things itself
        user = authenticate(username = username , password  = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('Index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
        else:
            print("login failed")
            print("username -> {} ||| password -> {}".format(username,password))
            return HttpResponse("INVALID LOGIN DETAILS SUPPLIED")
    else:
        return render(request, 'basic_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Index'))


@login_required
def special(request):
    return HttpResponse("Logged In")

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-static-top">
        <div class="container">
                <div><a class="navbar-brand" href="{% url 'Index' %}">HOME</div>
                <div><a class="navbar-brand" style="color:black;" href="{% url 'admin:index' %}">Admin</a></div>
                <div><a class="navbar-brand" style="color:black;" href="{% url 'basic_app:Register' %}">Register</a></div>
                {% if user.is_authenticated %}
                    <div><a class="navbar-brand" style="color:black;" href="{% url 'Logout' %}">Logout</a></div>
                {% else %}   
                    <div><a class="navbar-brand" style="color:black;" href="{% url 'basic_app:user_login' %}">Login</a></div>  
                {% endif %}
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>This is Index.html</h1>
    </div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Login</h1>
        <form action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password:</label>
            <input type="password" name="password">
            <input type="submit" value="Login" class="btn btn-primary">
        </form>
    </div>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thankyou For Registering!</h1>
        {% else %}
            <h1>Register Here</h1>
            <h2>Fill out the form:</h2>

            <!-- enctype is to allow image uploading if it is not there img uploading wont work -->
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type = 'submit' value="Register" class="btn btn-primary">
            </form>

        {% endif %}
    </div>

{% endblock %}